// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8IvWns-LSwGyYyXTy1HJel_pqOF7OkFA',
    appId: '1:832644182173:web:6ad79a9bbb7ddd62762474',
    messagingSenderId: '832644182173',
    projectId: 'plantcare-46fb7',
    authDomain: 'plantcare-46fb7.firebaseapp.com',
    storageBucket: 'plantcare-46fb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOp0KMhJKDw_g6en6GdqUpXxAsAqx_bd8',
    appId: '1:832644182173:android:f546d758c3d39d56762474',
    messagingSenderId: '832644182173',
    projectId: 'plantcare-46fb7',
    storageBucket: 'plantcare-46fb7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8IvWns-LSwGyYyXTy1HJel_pqOF7OkFA',
    appId: '1:832644182173:web:026c16639c0eae87762474',
    messagingSenderId: '832644182173',
    projectId: 'plantcare-46fb7',
    authDomain: 'plantcare-46fb7.firebaseapp.com',
    storageBucket: 'plantcare-46fb7.firebasestorage.app',
  );
}
